/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package my.bjgui;

import java.awt.*;
import javax.swing.*;
/**
 *
 * @author bnort
 */
public class BJGUITEST extends javax.swing.JFrame {

    /** Creates new form BJGUITEST */
    public BJGUITEST() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        superPanel = new javax.swing.JPanel();
        jPanelMainMenu = new javax.swing.JPanel();
        jButtonPlay = new javax.swing.JButton();
        jButtonUser = new javax.swing.JButton();
        jButtonExit = new javax.swing.JButton();
        jPanelUser = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButtonMenuReturnfromUser = new javax.swing.JButton();
        jPanelPlay = new javax.swing.JPanel();
        jButtonMenuReturnfromPlay = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(208, 208, 208));

        superPanel.setLayout(new java.awt.CardLayout());

        jButtonPlay.setBackground(new java.awt.Color(11, 211, 211));
        jButtonPlay.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jButtonPlay.setForeground(new java.awt.Color(248, 144, 231));
        jButtonPlay.setText("Play");
        jButtonPlay.setDefaultCapable(false);
        jButtonPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlayActionPerformed(evt);
            }
        });

        jButtonUser.setBackground(new java.awt.Color(11, 211, 211));
        jButtonUser.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jButtonUser.setForeground(new java.awt.Color(248, 144, 231));
        jButtonUser.setText("Choose User");
        jButtonUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUserActionPerformed(evt);
            }
        });

        jButtonExit.setBackground(new java.awt.Color(11, 211, 211));
        jButtonExit.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jButtonExit.setForeground(new java.awt.Color(248, 144, 231));
        jButtonExit.setText("Exit");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanelMainMenuLayout = new org.jdesktop.layout.GroupLayout(jPanelMainMenu);
        jPanelMainMenu.setLayout(jPanelMainMenuLayout);
        jPanelMainMenuLayout.setHorizontalGroup(
            jPanelMainMenuLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelMainMenuLayout.createSequentialGroup()
                .add(85, 85, 85)
                .add(jPanelMainMenuLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jButtonExit, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 150, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButtonUser, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 150, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButtonPlay, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 150, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(589, Short.MAX_VALUE))
        );
        jPanelMainMenuLayout.setVerticalGroup(
            jPanelMainMenuLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelMainMenuLayout.createSequentialGroup()
                .addContainerGap(234, Short.MAX_VALUE)
                .add(jButtonPlay, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 80, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jButtonUser, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 80, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jButtonExit, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 80, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(93, 93, 93))
        );

        superPanel.add(jPanelMainMenu, "mainMenuCard");

        jLabel3.setText("Please enter your name:");

        jButtonMenuReturnfromUser.setText("Return to Main Menu");
        jButtonMenuReturnfromUser.setToolTipText("");
        jButtonMenuReturnfromUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenuReturnfromUserActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanelUserLayout = new org.jdesktop.layout.GroupLayout(jPanelUser);
        jPanelUser.setLayout(jPanelUserLayout);
        jPanelUserLayout.setHorizontalGroup(
            jPanelUserLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelUserLayout.createSequentialGroup()
                .add(277, 277, 277)
                .add(jPanelUserLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel3)
                    .add(jTextField2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 141, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(406, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelUserLayout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jButtonMenuReturnfromUser)
                .addContainerGap())
        );
        jPanelUserLayout.setVerticalGroup(
            jPanelUserLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelUserLayout.createSequentialGroup()
                .add(208, 208, 208)
                .add(jLabel3)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jTextField2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 321, Short.MAX_VALUE)
                .add(jButtonMenuReturnfromUser)
                .addContainerGap())
        );

        superPanel.add(jPanelUser, "userCard");

        jButtonMenuReturnfromPlay.setText("Return to Main Menu");
        jButtonMenuReturnfromPlay.setToolTipText("");
        jButtonMenuReturnfromPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenuReturnfromPlayActionPerformed(evt);
            }
        });

        jLabel2.setText("This is the play card");

        org.jdesktop.layout.GroupLayout jPanelPlayLayout = new org.jdesktop.layout.GroupLayout(jPanelPlay);
        jPanelPlay.setLayout(jPanelPlayLayout);
        jPanelPlayLayout.setHorizontalGroup(
            jPanelPlayLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelPlayLayout.createSequentialGroup()
                .add(281, 281, 281)
                .add(jLabel2)
                .addContainerGap(448, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelPlayLayout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jButtonMenuReturnfromPlay)
                .addContainerGap())
        );
        jPanelPlayLayout.setVerticalGroup(
            jPanelPlayLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelPlayLayout.createSequentialGroup()
                .addContainerGap(390, Short.MAX_VALUE)
                .add(jLabel2)
                .add(165, 165, 165)
                .add(jButtonMenuReturnfromPlay)
                .addContainerGap())
        );

        superPanel.add(jPanelPlay, "playCard");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(superPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(superPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jButtonUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUserActionPerformed
        CardLayout card = (CardLayout)superPanel.getLayout();
        card.show(superPanel, "userCard");
    }//GEN-LAST:event_jButtonUserActionPerformed

    private void jButtonPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlayActionPerformed
        CardLayout card = (CardLayout)superPanel.getLayout();
        card.show(superPanel, "playCard");
    }//GEN-LAST:event_jButtonPlayActionPerformed

    private void jButtonMenuReturnfromPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenuReturnfromPlayActionPerformed
        CardLayout card = (CardLayout)superPanel.getLayout();
        card.show(superPanel, "mainMenuCard");
    }//GEN-LAST:event_jButtonMenuReturnfromPlayActionPerformed

    private void jButtonMenuReturnfromUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenuReturnfromUserActionPerformed
        CardLayout card = (CardLayout)superPanel.getLayout();
        card.show(superPanel, "mainMenuCard");
    }//GEN-LAST:event_jButtonMenuReturnfromUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BJGUITEST.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BJGUITEST.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BJGUITEST.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BJGUITEST.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BJGUITEST().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonMenuReturnfromPlay;
    private javax.swing.JButton jButtonMenuReturnfromUser;
    private javax.swing.JButton jButtonPlay;
    private javax.swing.JButton jButtonUser;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanelMainMenu;
    private javax.swing.JPanel jPanelPlay;
    private javax.swing.JPanel jPanelUser;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JPanel superPanel;
    // End of variables declaration//GEN-END:variables
    
}
